name: Release

on: [ workflow_dispatch ]

jobs:
  BuildAndPublishImage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          cache: 'gradle'
      - name: Build and publish image
        run: ./gradlew bootBuildImage --imageName josergdev.azurecr.io/communify:test1 --publishImage

