name: Release

on: [ workflow_dispatch ]

jobs:
  BuildAndPublishImage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          cache: 'gradle'
      - name: Build and publish image
        run: |
          gradle properties -q | grep "name:" | awk '{print $2}' >> $PROJECT_NAME
          gradle properties -q | grep "version:" | awk '{print $2}' >> $PROJECT_VERSION
          ./gradlew bootBuildImage --imageName ${{ secrets.REGISTRY_HOST }}/${{ env.PROJECT_NAME }}:${{ env.PROJECT_VERSION }} --publishImage
        env:
          ISSUER_URI: ${{ secrets.ISSUER_URI }}
          JWK_SET_URI: ${{ secrets.JWK_SET_URI }}
          REGISTRY_HOST: ${{ secrets.REGISTRY_HOST }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

